### ISSUE TITLE
legend missing in graph

### ISSUE THREAD

**Issue by sabiqali** [rrazaghi/modbamtools#1]
Hi, 

I was trying to  implement this for some modified bams that we generated. The script seems to work find and the output file gets generated, but it seems that there is no legend or any way to interpret the data. 

We think that the colours represent the average methylation frequency but something to tell us what they mean exactly would be very useful. 

I have included a screenshot of the output that i get. 

![Screenshot from 2022-04-06 10-44-27](https://user-images.githubusercontent.com/39552869/162001835-5746f42e-725f-4201-ab83-494a5a41daf7.png)

**Comment by rrazaghi** [comment]
Hi Sabiq,

Sorry, I am working on full documentation this week and hopefully, that will clarify things. 
You are right that the orange/blue in the top plot represents methylation frequency and the lines are just smoothed methylation frequency with savitzky-golay filter ( I'm planning on adding other smoothing methods soon)

**Comment by rrazaghi** [comment]
I'm adding some legends in the next release to address this

**Comment by rrazaghi** [comment]
New release and tutorial should mostly address this!
