### ISSUE TITLE
3+ haplotypes?

### ISSUE THREAD

**Issue by colindaven** [rrazaghi/modbamtools#11]
Hi,

this tool seems really nice, I'll be giving it a try soon. 

I wonder if you are planning - in future - to allow plotting, stats etc for more than 2 haplotypes ? 

Tools like whatshap polyphase and nPhase are starting to hopefully allow phasing of these tricky organisms.

Thanks

**Comment by colindaven** [comment]
Sorry, don't have anything yet, but might get back to you when I do. Hopefully within 4-6 months, but project not started yet ...

I'll get back to you.

**Comment by rrazaghi** [comment]
cool, I'll close this for now but do let me know when you are ready1

**Comment by OmarOakheart** [comment]
Hey, I developed nPhase, I also created a pipeline that streamlines the creation of artificial polyploid genomes: https://github.com/OmarOakheart/Phasing-Toolkit

You might be interested in this pipeline for creating a test dataset.

I also have an example dataset in https://github.com/OmarOakheart/nPhase/tree/master/example which can work if you just need a very small test case
