### ISSUE TITLE
How to sort Grch37 gtf file ?

### ISSUE THREAD

**Issue by xiucz** [rrazaghi/modbamtools#19]
Hi, 
Thank your for your tool, when I test it on my hg19 **bam** file  , but I find the downloaded data gtf file is based on 38. How to prepare to sort  the https://ftp.ebi.ac.uk/pub/databases/gencode/Gencode_human/release_42/GRCh37_mapping/gencode.v42lift37.annotation.gtf.gz file ?

Best,
xiucz

**Comment by yusmiatiliau** [comment]
Hi, I recently sort a gtf file using gff3sort that seems to work with modbamtools:
gff3sort.pl --precise /path/file.gtf > /path/filesorted.gtf
then bgzip and tabix:
bgzip -c /path/filesorted.gtf > /path/filesorted.gtf.gz
tabix -p gff /path/filesorted.gtf.gz

I installed gff3sort via bioconda:
https://anaconda.org/bioconda/gff3sort

hope it helps
